const USERS = {
    LOAD: "USERS_LOAD",
    LOAD_SUCCESS: "USERS_LOAD_SUCCESS",
    LOAD_FAIL: "USERS_LOAD_FAIL",
    ADD_USER: "USERS_ADD_USER",
    UPDATE_USER: "USERS_UPDATE_USER",
    SET_UPDATED_USER: "USERS_SET_UPDATED_USER",
    SET_ADDED_USER: "USERS_SET_ADDED_USER"
};

const ALERT = {
    CREATE_ALERT: "ALERT_CREATE_ALERT",
    CLOSE_ALERT: "ALERT_CLOSE_ALERT"
}

export { USERS, ALERT };
