const USERS = {
    LOAD: "USERS_LOAD",
    LOAD_SUCCESS: "USERS_LOAD_SUCCESS",
    LOAD_FAIL: "USERS_LOAD_FAIL",
    ADD_USER: "USERS_ADD_USER",
    SET_USER: "USERS_SET_USER"
};

const ALERT = {
    CREATE_ALERT: "ALERT_CREATE_ALERT",
    CLOSE_ALERT: "ALERT_CLOSE_ALERT"
}

export { USERS, ALERT };
